// Code generated by avro/gen. DO NOT EDIT.
package testpkg

import (
	"github.com/awaken/avro/v2"
)

var avroSchemaCacheTest = func() map[string]avro.Schema {
	cache := &avro.SchemaCache{}
	if _, err := avro.ParseWithCache("{\"doc\":\"Test is a test struct\",\"fields\":[{\"doc\":\"SomeString is a string\",\"name\":\"someString\",\"type\":\"string\"},{\"name\":\"someInt\",\"type\":\"int\"}],\"name\":\"a.b.test\",\"type\":\"record\"}", "", cache); err != nil {
		panic(err)
	}
	schemas := map[string]avro.Schema{}
	for _, name := range []string{
		"a.b.test",
	} {
		schema := cache.Get(name)
		if ref, ok := schema.(*avro.RefSchema); ok {
			schema = ref.Schema()
		}
		schemas[name] = schema
	}
	return schemas
}()

// Test is a test struct.
type Test struct {
	// SomeString is a string.
	SomeString string `avro:"someString"`
	SomeInt    int    `avro:"someInt"`
}

var schemaTest = avroSchemaCacheTest["a.b.test"]

// Schema returns the schema for Test.
func (o *Test) Schema() avro.Schema {
	return schemaTest
}

// Unmarshal decodes b into the receiver.
func (o *Test) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *Test) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
